Issue #291
Capgemini/dcx-react-library pull request #308
Opened 2022-07-08 10:42 UTC by SandraRoDiaz

2022-07-08 11:33 UTC, daniele-zurico commented on src/autocomplete/Autocomplete.tsx
> +
can you please remove this empty line?

2022-07-08 11:34 UTC, daniele-zurico commented on src/autocomplete/__tests__/Autocomplete.test.tsx
> +
same here can we remove all the empty lines?

2022-07-08 11:34 UTC, daniele-zurico commented on src/formInput/FormInput.tsx
> +
same here can we remove all the empty lines?

2022-07-08 13:54 UTC, Ibabalola requested changes

2022-07-08 13:54 UTC, Ibabalola commented on src/autocomplete/Autocomplete.tsx
> +   * Optional required flag
I feel we need a more descriptive comment here, required on its own doesn't reveal it's intended purpose

2022-07-08 13:54 UTC, Ibabalola commented on src/formInput/FormInput.tsx
> +   * Optional required flag
same - I feel we need a more descriptive comment here, required on its own doesn't reveal it's intended purpose

2022-07-08 13:54 UTC, Ibabalola commented on stories/Autocomplete/Styled.stories.mdx
> +          required
please update the Documentation.mdx also for Autocomplete and FormInput with the new required field.

2022-07-08 13:56 UTC, daniele-zurico commented on src/autocomplete/Autocomplete.tsx
> +   * Optional required flag
maybe something like:
`specifies if that an input field need to be filled ` could probably do the job?

2022-07-08 20:26 UTC, Ibabalola approved these changes

2022-07-11 10:21 UTC, daniele-zurico approved these changes

2022-07-11 10:26 UTC, merged