Fix: CharacterCount component not resetting red error text after valid input
Capgemini/dcx-react-library pull request #471
Opened 2023-05-05 09:20 UTC by nikkialgar

Fixes bug #463 where error class is assigned correctly when user inputs more than expected characters into CharacterCount component but didn't get removed.

#### Triggers error:

![Screenshot 2023-05-04 at 17 17 59](https://user-images.githubusercontent.com/229638/236420903-17378c6c-203c-4a43-8477-581da5ed97f8.png)

#### Resets error class when user corrects input:

![Screenshot 2023-05-04 at 17 18 07](https://user-images.githubusercontent.com/229638/236420922-b2acc399-0c78-49d6-9e4f-4f5904b8c2a2.png)

2023-05-05 12:53 UTC, daniele-zurico requested changes
Hi @nikkialgar thanks a lot for your PR.
Unfortunately, I just tried it and I can still see some behavior that is not correct.
One of the tests I did is to go over the limit and then select all the text and delete it. The counter reset back but the color of the text is still red

2023-06-15 08:25 UTC, byohannes commented
> Hi @nikkialgar thanks a lot for your PR. Unfortunately, I just tried it and I can still see some behavior that is not correct. One of the tests I did is to go over the limit and then select all the text and delete it. The counter reset back but the color of the text is still red

2023-06-15 08:28 UTC, byohannes commented
Hi @daniele-zurico, I have fixed the bug; please review in your time

2023-06-16 14:49 UTC, Ibabalola approved these changes

2023-06-16 15:38 UTC, merged