feat: Tabs are now non-js compliant
Capgemini/dcx-react-library pull request #506
Opened 2023-05-30 19:40 UTC by sri-viswanathan

- Add a specific class to tab panels when JS is disabled and use the `:target` CSS pseudoclass to show and hide content
- In `Tab.tsx`, replace `id` with `data-tab-id` as this was creating duplicate IDs on the page, i.e., both the tab and the tabpanel had the same value for the `id` attribute
- Update the `example` project to use React 18's `ReactDOM.createRoot` instead of `ReactDOM.render`
- Add `pointer-events: none;` when a tab is disabled

2023-06-27 16:12 UTC, Ibabalola commented
Hi, The Tab Component from dcx-library is not working in non-JS mode. In non-JS it is only showing the first tab content whereas we need all the content from all the tabs.

2023-06-27 16:17 UTC, Ibabalola requested changes
Hi @sri-viswanathan, The Tab Component from dcx-library is not working in non-JS mode. In non-JS it is only showing the first tab content whereas we need all the content from all the tabs.
https://design-system.service.gov.uk/components/tabs/default/index.html (disable js in the browser)

2023-07-07 10:53 UTC, sri-viswanathan commented
Hi @Ibabalola , ah, I see. I deliberately did it that way (i.e. displaying only the content for the active tab) but am happy to make the change to display the content for all tabs when JS is disabled.  Apart from that, can you please confirm that the right content displays when you click on different tabs with JS disabled or are you seeing only the first tab's content regardless of which tab you click?

2023-07-07 13:54 UTC, sri-viswanathan commented
Also @daniele-zurico , please can you confirm that release `0.8.0-rc1` contains the code from this PR?  The anchor tags for the tabs should have a new attribute called `data-tab-id` but I don't see that attribute when I use `0.8.0-rc1`.

2023-07-14 12:12 UTC, daniele-zurico approved these changes

2023-07-14 12:16 UTC, daniele-zurico approved these changes

2023-07-14 12:29 UTC, Ibabalola approved these changes

2023-07-14 12:30 UTC, merged