Icon has been added to the Form Select component!
Capgemini/dcx-react-library pull request #523
Opened 2023-08-30 12:29 UTC by Afshin-Karamifar

2023-08-31 11:11 UTC, Ibabalola requested changes

2023-08-31 11:11 UTC, Ibabalola commented on stories/liveEdit/FormSelectLive.tsx
> +      // options={['option1','option2', 'option3']}
it is not required to have both `options` and `option` commented out here because `options={['option1','option2', 'option3']}` is not applicable for this comment `If you need a more advanced control of options use the following`

2023-08-31 12:09 UTC, Ibabalola commented
after running the PR locally I am seeing this error:
```bash
Compiled with problems:X

ERROR in ./src/components/AutocompleteDemo.tsx 7:0-62

Module not found: Error: Can't resolve '@capgeminiuk/dcx-react-library' in '/Users/isaacbabalola/DevBuild/dcx-react-library/example/src/components'
```

2023-09-07 17:41 UTC, Afshin-Karamifar commented on stories/liveEdit/FormSelectLive.tsx
> +      // options={['option1','option2', 'option3']}
Thanks for your comment, I removed it!

2023-09-22 15:02 UTC, daniele-zurico reviewed
hi @Afshin-Karamifar I can see 2 things missed for sure:
1. there's no test for the files you changed and the coverage is now below 100%
2. the storybook documentation is not strong anymore ... we don't have the field you added in the documentation page nor an example in the styled or unstyled version

2023-11-21 15:32 UTC, closed without merging