create design system stories
Capgemini/dcx-react-library pull request #542
Opened 2023-10-07 16:39 UTC by jgonza16

Done!! hope all is well any suggestions are welcome👍🏼

2023-10-18 11:32 UTC, mmirca requested changes
Thank you for the amazing work Javi! Just have a few small suggestions, would love to hear your thoughts on these topics :)

2023-10-18 11:32 UTC, mmirca commented on src/design-system/abbreviate.css
> +  background: token('color-background-abbreviate');
Open question, should we have an abbreviate specific token? Maybe we could reuse the highlight_body?

I'm thinking every new token we add puts a bit more work on the end developer. More options to configure. For some components we might be able to make certain assumptions and reuse the tokens.

Also if we keep it as a new token we probably need to use it for the rest of properties as well. So we have for example:

font-family-abbreviate instead of font-family-body

What's your take on this? should we keep it as a different token?

2023-10-18 11:32 UTC, mmirca commented on src/design-system/tokens.json
> +  "color-background-abbreviate": "#9CCADD",
maybe for the default we can keep it as unopinionated as possible. Something like a transparent background might be a good default.

Same for the spacings, maybe we can keep it at 0px so it's just inlined with the rest of the text by default.

You think it would make sense?

2023-10-18 11:32 UTC, mmirca commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
It'd be really valuable to see this component next some text. It would help the developer understand the usage and also we could showcase how it looks like in a real scenario.

2023-10-21 07:15 UTC, jgonza16 commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
ok, it makes perfect sense, I would improve the documentation. I do it.

2023-10-21 07:48 UTC, jgonza16 commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
When trying to create the example with the 'paragraph' component, it's not really usable with 'abbreviate' since it only accepts a string. What do you think about the change to make it accept children?

<img width="532" alt="image" src="https://github.com/Capgemini/dcx-react-library/assets/93665374/47ea85e7-252a-4613-8c31-d5e4c69bc394">

2023-10-23 14:40 UTC, cg-mmirca commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
@daniele-zurico maybe we should consider support for children in paragraph?

2023-10-26 14:28 UTC, daniele-zurico commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
@jgonza16 and @cg-mmirca yes I agree with both of you. Adding children will make the component more easy to be used and more general purpose.

@jgonza16 do you want to make the changes yourself or you want me to do it?
changes needed:

- [ ] make the change in the src/abbreviate/Abbreviate.tsx adding the property
- [ ] make the change in the src/abbreviate/__tests__/Abbreviate.test.tsx adding the test to cover the use case
- [ ] change all the storybook sections to add the documentation
(it's an easy change but we need to touch on different places and to be honest with you I'm start feeling is not the only component that should allow that but most of the typography one should have this ability)

how do we want to proceed?

2023-11-01 18:13 UTC, jgonza16 commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
@daniele-zurico  I think that the best approach is only children and remove prop value but this is a breaking change. you could make new ticket with all typography component to change and you assign it to me. i do it👌🏼.

2023-11-01 18:31 UTC, jgonza16 commented on src/design-system/abbreviate.css
> +  background: token('color-background-abbreviate');
i think fewer token is better for the end developer too. I change specific token for highlight_body. Great question MARIUS.

2023-11-01 18:44 UTC, jgonza16 commented on src/design-system/tokens.json
> +  "color-background-abbreviate": "#9CCADD",
it makes perfect sense. the unopinionated way is better but in this case I would only change spacing to 0px becouse i choose remove abbreviate token.

2023-11-01 18:49 UTC, jgonza16 commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
we can stop this ticket until the new is completed and i can do better stories here.

2023-11-02 13:26 UTC, daniele-zurico commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
@jgonza16 ticket created https://github.com/Capgemini/dcx-react-library/issues/566 and assigned to you. I think we can hold this ticket and complete the other one first

2023-11-07 11:27 UTC, daniele-zurico commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
Ticket #566 closed and changes implemented

2023-11-11 10:33 UTC, jgonza16 commented on stories/Abbreviate/design-system/DarkTheme.stories.js
> +    value: 'ASAP',
it's ready!!

<img width="1041" alt="image" src="https://github.com/Capgemini/dcx-react-library/assets/93665374/7184ce5a-3dbc-4437-aa3b-082036509107">

2023-11-17 11:40 UTC, mmirca approved these changes

2023-11-17 11:43 UTC, merged