Link Design-System: Default and Accessible themes
Capgemini/dcx-react-library pull request #545
Opened 2023-10-10 09:03 UTC by JadhavJeet

2023-10-18 13:21 UTC, cg-mmirca requested changes
Thank you Jeet for the amazing work! I just see some small improvements we might want to tackle before merging.

2023-10-18 13:21 UTC, cg-mmirca commented on src/design-system/link.css
> +  &.dcx-link-visited {
Should we consider the active state as well?

2023-10-18 13:21 UTC, cg-mmirca commented on src/design-system/link.css
> +  &.dcx-link-visited {
I think it's better if we handle the visited state on CSS instead of depending on an external class.

Should be easier for the end users of the library if we don't put this work on them. Maybe we can use the pseudoselector `:visited` instead?

2023-10-26 14:33 UTC, JadhavJeet commented on src/design-system/link.css
> +  font-size: token('font-action_label-size');
fixed

2023-10-26 14:34 UTC, JadhavJeet commented on src/design-system/link.css
> +  &.dcx-link-visited {
sure, can you pls guide me in how should we demonstrate active state link

2023-10-26 14:34 UTC, JadhavJeet commented on src/design-system/link.css
> +  &.dcx-link-visited {
done

2023-11-02 11:00 UTC, cg-mmirca approved these changes

2023-11-02 11:01 UTC, merged