Range Design System
Capgemini/dcx-react-library pull request #662
Opened 2024-06-14 10:07 UTC by Ahmet-K

https://github.com/Capgemini/dcx-react-library/issues/595

2024-06-17 08:51 UTC, alexwbbr commented on src/design-system/range.css
> +    height: 25px;
please can you add this to the css token

2024-06-17 08:51 UTC, alexwbbr commented on src/design-system/range.css
> +    height: 25px;
same here for height and width

2024-06-17 08:52 UTC, alexwbbr commented on src/design-system/range.css
> +    background: #04AA6D;
same here for height and width and the background colour

2024-06-17 08:53 UTC, alexwbbr commented on stories/themes/dark.theme.css
> +  --dcx-color-outline-formcontrol: red;
please use more of the tokens and create a better dark theme for the slider. Look at the other examples to see what colours to use and what to change

2024-06-18 15:39 UTC, jgonza16 requested changes
First of all, thanks for the work!!
Just some suggestions.

1. We must use tokens for everything related to colors, sizes, etc. to later be able to customize. As long as you can use existing ones of the same type (formcontrol) as you used border-radius-formcontrol ok. Perhaps in this case you will need to generate new tokens for the thumb appearance, following the pattern documented in the ticket.

2. The Range should have a look and feel similar to this in my opinion.
![image](https://github.com/Capgemini/dcx-react-library/assets/93665374/dc26eef9-4f58-4d01-a31a-2885eb8b6863)

If you need anything you can write to me directly javier.gonzalez-moya@capgemini.com

2024-06-21 09:36 UTC, Ahmet-K commented on src/design-system/range.css
> +    height: 25px;
Done.

2024-06-21 09:37 UTC, Ahmet-K commented on src/design-system/range.css
> +    height: 25px;
Done.

2024-06-21 09:37 UTC, Ahmet-K commented on src/design-system/range.css
> +    background: #04AA6D;
Done.

2024-06-21 09:37 UTC, Ahmet-K commented on stories/themes/dark.theme.css
> +  --dcx-color-outline-formcontrol: red;
Done.

2024-06-24 14:55 UTC, alexwbbr commented
Please can you check the following @Ahmet-K :

- The main design system docs for range doesn't load properly in storybook due to an error
- The playground for the design system doesn't load properly in storybook due to an error
- The tokens you have created are missing in the tokens.json file in the design system folder and as such the range won't have a default design. (please see button component for a comparison)
- Please give the names of the tokens you have created more descriptive names such as "range-track-height" instead of "track-height" as this will give users a better understanding of what each token controls.
- Please double check the base css as there are properties that can be moved to tokens. Such as the outline for the thumb (line 30), the z-index values (lines 20 and 42), the border for the disabled state (line 47) and the border radius on line 17

2024-06-28 13:07 UTC, alexwbbr commented on src/design-system/tokens.json
> +  "border-radius-range-thumb": "8px",
please change to 50%

2024-06-28 13:18 UTC, alexwbbr approved these changes, later dismissed

2024-06-28 19:24 UTC, jgonza16 requested changes
Great job!! I just have a few small suggestions.

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/range.css
> +.dcx-range::-webkit-slider-thumb {
here we can use post css nesting. 
```css
.dcx-range {
// css rules 
 &::-webkit-slider-thumb {
   // css rules 
     &:hover {
      }
  }
  &::before {
  }
}
```

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/tokens.json
> +  "border-radius-range-thumb": "8px",
we must follow the naming pattern [property]-[element]-[variant]-[state] and i suggest use formcontrol common name instead range single component name.
- property: border-radius
- element: formcontrol_thumb
- variant: none
- state: none

name: border-radius-formcontrol_thumb

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/tokens.json
> +  "color-range-thumb": "blue",
we must follow the naming pattern [property]-[element]-[variant]-[state] and i suggest use formcontrol common name instead range single component name.
- property: background-color
- element: formcontrol_thumb
- variant: none
- state: none

name: background-color-formcontrol_thumb

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/tokens.json
> +  "color-range-thumb-hover": "darkblue",
we must follow the naming pattern [property]-[element]-[variant]-[state]
- property: background-color
- element: range_thumb
- variant: none
- state: hover

name: background-color-range_thumb-hovet

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/tokens.json
> +  "range-thumb-width": "20px",
we must follow the naming pattern [property]-[element]-[variant]-[state]
- property: height
- element: formcontrol_track
- variant: none
- state: none

name: height-formcontrol_track

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/range.css
> +  position: relative;
We need add cursor pointer here because you can do click in track element.

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/range.css
> +  background: token('color-range-thumb');
here we can use the formcontrol common token color-outline-formcontrol. This way it will be in harmony with the other components of the form

2024-06-28 19:24 UTC, jgonza16 commented on src/design-system/range.css
> +  background-color: token('color-background-formcontrol_label-floating-filled');
here we can't use label formcontrol token. we can create new background-color-formcontrol_track

2024-07-01 10:47 UTC, Ahmet-K commented on src/design-system/range.css
> +.dcx-range::-webkit-slider-thumb {
Done.

2024-07-01 13:39 UTC, Ahmet-K commented on src/design-system/tokens.json
> +  "range-thumb-width": "20px",
@jgonza16  
My suggestions are below. Please confirm it.

range-thumb-width => width-formcontrol_thumb
range-thumb-height => height-formcontrol_thumb
range-track-height => height-formcontrol_track

2024-07-01 14:43 UTC, Ahmet-K commented on src/design-system/range.css
> +  position: relative;
Done. I have also changed the cursor pointer default for disabled elements.

2024-07-01 14:55 UTC, Ahmet-K commented on src/design-system/tokens.json
> +  "border-radius-range-thumb": "8px",
Done.

2024-07-01 14:55 UTC, Ahmet-K commented on src/design-system/range.css
> +  background-color: token('color-background-formcontrol_label-floating-filled');
Done.

2024-07-01 14:56 UTC, Ahmet-K commented on src/design-system/range.css
> +  background: token('color-range-thumb');
used new `color-background-formcontrol_thumb` token.

2024-07-01 14:57 UTC, Ahmet-K commented on src/design-system/tokens.json
> +  "color-range-thumb-hover": "darkblue",
Done.

2024-07-01 14:58 UTC, Ahmet-K commented on src/design-system/tokens.json
> +  "color-range-thumb": "blue",
Done.

2024-07-01 14:58 UTC, Ahmet-K commented on src/design-system/tokens.json
> +  "color-range-thumb": "blue",
Done.

2024-07-04 13:38 UTC, jgonza16 commented on src/design-system/tokens.json
> +  "range-thumb-width": "20px",
yep you are right

2024-07-04 19:30 UTC, jgonza16 approved these changes

2024-07-04 19:35 UTC, jgonza16 approved these changes, later dismissed

2024-07-04 19:40 UTC, jgonza16 approved these changes

2024-07-04 19:42 UTC, merged