Fix/accordion click event
Capgemini/dcx-react-library pull request #665
Opened 2024-06-19 10:52 UTC by alexsteele95

Removed (seemingly unnecessary - correct me if I'm wrong!) selected logic and migrated onClick behaviour to the title component so that the click box only effects the title (and not the details).

2024-06-26 13:14 UTC, Ibabalola requested changes
Hi @alexsteele95 , can you add an example of the accordion to the demo page, I've not mistaken it is currently not there.

![Screenshot 2024-06-26 at 14 11 07](https://github.com/Capgemini/dcx-react-library/assets/11960286/eb3bd59f-e58a-4128-b33c-0e7f82f1c0c1)

Looking at the changelog the Accordion component was release in version "1.0.0"

2024-06-27 09:29 UTC, daniele-zurico commented on src/accordion/AccordionTitle.tsx
> +  const { onClick } = useContext(AccordionContext);
it could be nice to have a test that:
1. make sure that on click on the title it does something
2.on click on the other element does nothing

2024-07-10 14:52 UTC, Ibabalola submitted a review, later dismissed

2024-07-10 15:13 UTC, Ibabalola approved these changes

2024-07-10 15:15 UTC, merged