Add avatar component
Capgemini/dcx-react-library pull request #689
Opened 2024-09-06 15:27 UTC by cg-julian-taylor

2024-09-10 08:34 UTC, alexwbbr commented
@cg-julian-taylor please can you alter the without style avatar documentation to use the text instead of the link. I also think when using the external link you shouldn't see text
<img width="64" alt="Screenshot 2024-09-10 at 09 33 11" src="https://github.com/user-attachments/assets/84a04b04-69b5-46d0-a296-635c3b38dfef">
The link should just accept a url and maybe some aria labels, when using the external link you should be able to see the image or text

2024-09-10 08:46 UTC, cg-julian-taylor commented
No problem with changing the without style documentation. It does look a bit odd.

As for what you pass in to the avatar itself I believe you should be able to pass in an aria-label as a prop.
You can pass in whatever child components you wish, e.g. an SVG.

I assume the typical use case of passing an image url or initials, however I wanted to demonstrate that the contents are flexible so used an external link as that was the most likely use case I could think of adding.

I also made the assumption that if a user is injecting something such as an SVG they would manipulate styling.

However if I am wrong or you disagree please let me know what use cases I should aim for.

2024-09-11 15:30 UTC, alexwbbr commented on src/avatar/Avatar.tsx
> +        backgroundColor: backgroundColourOptions[backgroundColourOption],
Please can you remove this property. As we are css agnostic we want to include the minimum css possible for the component to work.
This also poses an issue when trying to overwrite the background colour to be a custom colour, as the background colour is being set on the element directly only adding !important in a class or passing it through in the style props directly will change the colour

2024-09-11 15:33 UTC, alexwbbr commented
@cg-julian-taylor can you please remove the design system folder from storybook as it is currently broken. It will be picked up in a separate ticket as it requires a bit more work.

2024-09-11 15:35 UTC, alexwbbr commented on src/avatar/Avatar.tsx
> +        width: '40px',
can you please move the width and height to be properties the user can enter. We can default them to 40px each but they should be easy to change rather than passing in extra properties in a style attribute

2024-09-23 09:58 UTC, alexwbbr commented on stories/Avatar/Documentation.mdx
> +type SharedProps = React.HTMLAttributes<HTMLElement> & {
Please have a look at the other documentation and update this section. It is a section where you give an example of how the component is used with all possible attributes. It is not a section where you copy the code for the component

2024-09-23 10:00 UTC, alexwbbr commented on stories/Avatar/Documentation.mdx
> +};
You are also missing the section of the documentation where all the properties are listed
```

Below a list of all the available properties:

<ArgTypes of={ButtonStories} />
```
taken from the button documentation

2024-09-23 10:04 UTC, alexwbbr commented on src/avatar/Avatar.tsx
> +  const backgroundColor =
As I have mentioned previously please remove the background colour property entirely. It is not needed.

2024-09-23 10:09 UTC, alexwbbr commented on src/avatar/Avatar.tsx
> +  wrappingAnchorHref?: string;
please rename this property and rewrite the description. A user does not need to know it's a wrapping href or an anchor tag. It should be something like avatarLink, Where a user can pass in a url and when the avatar component is clicked the link will open

2024-09-23 10:10 UTC, alexwbbr commented on src/avatar/Avatar.tsx
> +  wrappingAnchorTarget?: '_blank' | '_self' | '_parent' | '_top';
I like that this property has been included but again please rename it to be something different along with the documentation. AvatarLinkTarget etc. Tell the user what the property does and not a description of the code it adds

2024-09-23 10:12 UTC, alexwbbr commented on src/avatar/Avatar.tsx
> +type ImageAvatarProps = SharedProps & {
please remove these two additions types. Having SharedProps, AvatarProps, and ImageAvatarProps is not needed. Simply add src and alt to the main type and make them optional

2024-12-05 11:31 UTC, omkarkulkarni2704 approved these changes

2024-12-05 15:03 UTC, omkarkulkarni2704 approved these changes

2025-01-08 15:50 UTC, omkarkulkarni2704 requested changes

2025-01-08 15:50 UTC, omkarkulkarni2704 commented on src/avatar/__tests__/Avatar.test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react';
You imports ```render``` and ```screen``` twice, which is redundant and will cause a conflict.

```import { render, screen } from '@testing-library/react';```
```import { fireEvent, render, screen } from '@testing-library/react';```

Corrected code is:-
You can combine the imports into a single line to avoid redundancy:

```import { render, screen, fireEvent } from '@testing-library/react';```

2025-01-08 15:57 UTC, cg-julian-taylor commented on src/avatar/__tests__/Avatar.test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react';
Im a bit confused I cant see a second import statement?

2025-01-08 16:10 UTC, omkarkulkarni2704 commented on src/avatar/__tests__/Avatar.test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react';
I am saying, the second import statement unnecessarily re-imports ```render``` and ```screen```, which were already imported. To avoid duplication, combine them into one line like this:

```import { render, screen, fireEvent } from '@testing-library/react';```

2025-01-08 16:15 UTC, cg-julian-taylor commented on src/avatar/__tests__/Avatar.test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react';
I can see a deletion of `import { render, screen } from '@testing-library/react';` and an addition of `import { fireEvent, render, screen } from '@testing-library/react';` 

I may be misreading the information.

Either way I have a bit more work to do so shall make sure to double check the work before submitting.

2025-01-08 16:19 UTC, omkarkulkarni2704 commented on src/avatar/__tests__/Avatar.test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react';
Ok.

2025-01-29 13:43 UTC, Ibabalola commented on src/avatar/Avatar.tsx
> +          src={`${process.env.BASE_URL}/${process.env.AVATAR_FALLBACK_IMAGE}`}
Question: what happens here if the consumer does not configure these environment variables?

```
* If `children` props are passed they will be rendered.
* If no `children` props are passed then the first letter of the `alt` prop will be rendered.
* If the `alt` prop is not present then a default image will be loaded.
```

The documentation reads in such a way that it looks to be the library that provides the default image

2025-01-29 14:42 UTC, cg-julian-taylor commented on src/avatar/Avatar.tsx
> +          src={`${process.env.BASE_URL}/${process.env.AVATAR_FALLBACK_IMAGE}`}
This is a good question, and one that I have asked elsewhere. So yes the library would provide a default, but I assume someone using this library may want to swap out or supply their own. Hence the ENV variables.

Short answer is this wouldn't work if you didn't configure ENV vars but am unsure what is an acceptable alternative.

Im open to suggestions. Theres lots of ways of doing this but am unsure what is the preferred approach for this instance.

2025-01-29 16:35 UTC, daniele-zurico commented on src/avatar/Avatar.tsx
> +          src={`${process.env.BASE_URL}/${process.env.AVATAR_FALLBACK_IMAGE}`}
why not doing something more easy like this:
```jsx
<img 
     onError={e => {}}
```

2025-01-30 13:39 UTC, cg-julian-taylor commented on src/avatar/Avatar.tsx
> +          src={`${process.env.BASE_URL}/${process.env.AVATAR_FALLBACK_IMAGE}`}
So the reason for the more complex approach is so that when an image is loaded and fails we can fall back to a different rendering method. Inspired by MUI. So we would render children, and alt tags first letter or a default image.

I may be missing out on a more simple way of implementing the same behaviour though.
This seemed to be a good way of accomplishing what we wanted.

2025-01-30 14:58 UTC, daniele-zurico commented on src/avatar/Avatar.tsx
> +          src={`${process.env.BASE_URL}/${process.env.AVATAR_FALLBACK_IMAGE}`}
yeah @cg-julian-taylor your way is not bad I'm just thinking that ENV variable that is a bit weird to remember to configure... maybe instead of `process.env.AVATAR_FALLBACK_IMAGE` we can provide an extra param called `avatarFallbackImage`?
cc @Ibabalola

2025-01-30 15:42 UTC, cg-julian-taylor commented on src/avatar/Avatar.tsx
> +          src={`${process.env.BASE_URL}/${process.env.AVATAR_FALLBACK_IMAGE}`}
Very happy to do this. I did originally consider this but then thought if you have to add multiple avatars you have to remember to do it for each. But I'll pass the `avatarFallbackImage` prop as you suggested. Its a bit more standard practice.

2025-02-17 10:46 UTC, cg-julian-taylor commented on src/avatar/Avatar.tsx
> +          src={`${process.env.BASE_URL}/${process.env.AVATAR_FALLBACK_IMAGE}`}
This has now been done. Apologies for the delay.

2025-02-17 13:01 UTC, Ibabalola submitted a review, later dismissed

2025-02-24 17:21 UTC, alexwbbr submitted a review, later dismissed

2025-03-04 10:18 UTC, daniele-zurico approved these changes

2025-03-04 10:19 UTC, merged